2024-11-27 19:05:24,127 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 19:05:24,623 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 19:06:13,689 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (3 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 19:06:13,690 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (3 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 19:06:57,118 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (3 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 19:06:57,119 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (3 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 19:07:28,081 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 19:07:28,082 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 19:07:57,553 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 19:07:57,553 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 19:08:35,985 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (3 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 19:08:35,986 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (3 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 19:09:29,425 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 19:09:29,426 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 19:09:55,199 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 19:10:06,111 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 19:10:07,508 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 19:10:27,962 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 19:10:27,962 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 19:11:42,797 ERROR: RSAΩ‚√‹¥ÌŒÛ: argument should be a bytes-like object or ASCII string, not 'bool' [in d:\Code\project\Auth\app\utils.py:106]
2024-11-27 19:11:42,797 ERROR: Ω‚√‹ ß∞‹: argument should be a bytes-like object or ASCII string, not 'bool' [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 19:12:24,313 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 19:12:24,313 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:20:03,444 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:20:03,444 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:20:29,939 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:20:29,939 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:21:56,477 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:21:56,477 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:22:44,424 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:22:44,424 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:28:22,699 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (128 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:28:22,700 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (128 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:31:36,845 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:31:36,845 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:34:08,034 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:34:08,034 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:35:50,014 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:35:50,014 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:36:49,717 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:36:49,717 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:37:41,385 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (3 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:37:41,385 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (3 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:38:14,913 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:38:14,913 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (64 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:39:01,794 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 20:44:53,710 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:44:53,712 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:45:53,252 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:45:53,252 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:48:38,847 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:48:38,848 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:49:29,984 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 20:50:15,968 ERROR: AESΩ‚√‹¥ÌŒÛ: Padding is incorrect. [in d:\Code\project\Auth\app\utils.py:91]
2024-11-27 20:50:15,968 ERROR: IV≥§∂»: 16 [in d:\Code\project\Auth\app\utils.py:92]
2024-11-27 20:50:15,968 ERROR: IV: b'&\xeezA\xfd\xc9\xcc&\xba\xb0\xb8\xf9\xd2":\x19' [in d:\Code\project\Auth\app\utils.py:93]
2024-11-27 20:50:15,970 ERROR: √‹Œƒ: 45wSeRRrCXZXhW7Dx0OMo5uQZX85SlssxN5MUpABGW22RYPUSPlnVOU7m2EnxYl7 [in d:\Code\project\Auth\app\utils.py:94]
2024-11-27 20:50:15,970 ERROR: Ω‚√‹ ß∞‹: Padding is incorrect. [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 20:52:28,488 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 20:53:03,703 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 20:53:04,122 INFO: RSA√‹‘ø∂‘…˙≥…≥…π¶ [in d:\Code\project\Auth\app\__init__.py:35]
2024-11-27 20:53:35,844 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 20:54:47,775 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 20:54:47,775 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:02:41,194 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:02:46,148 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:02:52,931 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:02:57,838 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:03:03,290 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:09:18,512 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:87]
2024-11-27 21:09:18,512 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:11:36,366 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:11:36,725 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:11:48,791 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:11:49,951 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:11:54,603 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:12:22,119 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:12:48,192 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:12:52,807 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:12:55,463 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:12:58,071 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:13:28,974 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:13:50,407 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\utils.py:84]
2024-11-27 21:13:50,407 ERROR: Ω‚√‹ ß∞‹: Incorrect IV length (it must be 16 bytes long) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 21:14:09,105 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 21:14:11,130 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
