2024-11-27 17:09:09,641 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:09:12,156 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:09:16,353 ERROR: RSAΩ‚√‹¥ÌŒÛ: Incorrect decryption. [in d:\Code\project\Auth\app\utils.py:103]
2024-11-27 17:09:16,354 ERROR: Ω‚√‹ ß∞‹: Incorrect decryption. [in d:\Code\project\Auth\app\routes.py:41]
2024-11-27 17:11:45,807 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:11:53,465 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:11:56,040 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:12:00,644 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:12:02,656 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:12:08,889 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:12:11,686 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:12:13,787 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:12:17,281 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:12:21,687 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:12:26,753 ERROR: RSAΩ‚√‹¥ÌŒÛ: Incorrect decryption. [in d:\Code\project\Auth\app\utils.py:104]
2024-11-27 17:12:26,754 ERROR: Ω‚√‹ ß∞‹: Incorrect decryption. [in d:\Code\project\Auth\app\routes.py:41]
2024-11-27 17:13:10,923 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:13:44,262 ERROR: RSAΩ‚√‹¥ÌŒÛ: Incorrect decryption. [in d:\Code\project\Auth\app\utils.py:104]
2024-11-27 17:13:44,262 ERROR: Ω‚√‹ ß∞‹: Incorrect decryption. [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:25:53,191 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:26:00,887 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:26:05,407 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:26:05,891 INFO: RSA√‹‘ø∂‘…˙≥…≥…π¶ [in d:\Code\project\Auth\app\__init__.py:35]
2024-11-27 17:26:45,658 INFO: ø™ ºRSAΩ‚√‹ [in d:\Code\project\Auth\app\routes.py:23]
2024-11-27 17:26:45,693 ERROR: RSAΩ‚√‹¥ÌŒÛ: Incorrect decryption. [in d:\Code\project\Auth\app\utils.py:116]
2024-11-27 17:26:45,693 ERROR: ÀΩ‘ø¿‡–Õ: <class 'bytes'> [in d:\Code\project\Auth\app\utils.py:117]
2024-11-27 17:26:45,694 ERROR: ÀΩ‘øƒ⁄»›: b'-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA1h97jM5TkUl2H3wi3seUI8JFqPg9ysn6cOLDfc3zelhSxNHC\nqNzfRiDdj8bc4lF0gfB+fcyNtpMXm+cPKnL2AKZAL03p3OVYdEogwCBp3W4oPT2I\nLX+pggLPAKYvZmvC1aUjYFNLQjVsCg2xlEqW6qINzRxeprmU096RjO8upPDDPgJ9\nmShWjguLT/UwLgpbLmMMkqzUGmbpBFMrUtVniYNnTvE3bg0ghyGsEnyhdsh3SUGP\ngxqtTcMjRleDg1nVG2XNwEr0D1tg2+ZHhC+scmLzeDDvMh1c9tparRg30imbCQ30\nxGwU7hJLxVe8auCq+rX/EI2xI0c57jpy5Bz/mQIDAQABAoIBAEUqRzz8+tZ/7cWO\n0i63Nh106A6EHWWvZ5PmU/KDv8XB2P6VqTTln8Ol4xvJx1jdqe49MobNN+uFSQeF\nlAsItnkQOsRs/QFrHe72cOzOq5OovRvHEAFubuE9qgMSK1aAsZ9UaAB592HsIrl+\noeF+VJB3B1E9fD+Ly8zCZK6rJhyFx6idaSwqLTLOVz1fh1rNMLHW4r/50XW0Xj3v\nyxzWhLNt9PdX13xBh8KfQhzmB0oxm111rORYPyPLwhL5eono1dSitnYkh0oTlMQ1\nlX9pv7Mnk63zucbNpq8Nx9BsQHZ7kI4SagYWwCa26Uipxg+M+23ed5VGqolXOTHE\nK4Ok908CgYEA5QrlYo+3ieJy+PJCvarzKIH/x014at0fYx4Klrb3l+9DADFgEZhg\nglWCkylhPEWikApAmoxi+NjG5feL2e6qjneyYZKbUwMziOB58CZlLwfrUNGuBK7Y\nQy+b0g75D8nntv6PpGyknOury9WFvpSXr87XBJC9AyUYHz308yRCZpcCgYEA71MO\nYQqlS9npRFQAWlWdZgslgt+CSK3V+korkbFgydEVtEIh0R3sRk0PWkIv+ypBoazO\ndwQpxvJK+MAhGS/vOFoiJMo6dkxEflu9GdskhqfwJhsKF+vQS7tBLwBBKbRL1783\nNnCe42T8m8q04Z1KdndNMYl6+tGeXs1A8VJlQU8CgYA3FgHJTKtl3DKusQVgPIcy\nzOFJe9ZkTT5JRmZhjSvLPN4uY7GpSa6cahh3cFJUfqL0ZaLYCL+c/fYIRRs7lO0s\nSpl6Yho9Qt3YI7TwDyvyvcLYszVZJvwYXJDrWnKIW5UBLAQ8FW0Z2Ix+/6GlDnPU\n8rg//teWtAszKGGLQMM/jQKBgQDAVXJ/4KtZGyaRyCSEdLvLL3gVBoVQ3YvS21rK\nes/7QXJ87Iz6315sXS/SbNDcvGgEg7lmAs2EWmKQKPAwqspI8n7wLCnxundtSVLe\n/bQMF9ky9pYVBWngAvxuxniYCJLPL5gywy2eOCGfHrhhfSRDsrsx7XgNLPtm2vOv\nPXWslwKBgQDbS4M8cc2iYvzr5D5RuFjuR8l5ia5ZqenhpVRrWFs7Iz4v4ijlL+Eo\nCbtvWFzocdIGrTKxVnx+NTfy3LeO4SK9TRhL2ddkNUe1MGVIfa9Nfzmkbri20wZA\nARNgecD6THUeDORdT5t7BHHKSmjDd9p6Ci8G0J9tzrCToder0M5DjA==\n-----END RSA PRIVATE KEY-----' [in d:\Code\project\Auth\app\utils.py:118]
2024-11-27 17:26:45,695 ERROR: º”√‹ ˝æ›¿‡–Õ: <class 'str'> [in d:\Code\project\Auth\app\utils.py:119]
2024-11-27 17:26:45,695 ERROR: º”√‹ ˝æ›ƒ⁄»›: 0QzIsdsVnn6xziKkpUgmXNnfHLjOnDdWIBWI2u47khfUgpPFljCvL3ja3+suzya/d6dqqTlOFb98sAhm0DDQiyPxuFB4arhcLMzTwXveCGpFadl5NT5GezCSL7Jsj0j1tE74Hdi9aMKdEYQDCeR981NNt0+PaqrfnfrA3MT6aOo55Hbp1kwUgSyxeQDSMT+kHgn64hmLeI0Esjbqomf4KjWwMOvd1uH6KqaGUyg8xqLCYoQYPyD1vsvDreLQfYH7qfItP06Utt1mZCMhkuLfcuMCT6P1Fwtd3AdNCV23ufIiE4bUac7RKxDrCwqB2+k77GbFNt3LQ3kdGWSkozbl3Q== [in d:\Code\project\Auth\app\utils.py:120]
2024-11-27 17:26:45,695 ERROR: Ω‚√‹ ß∞‹: Incorrect decryption. [in d:\Code\project\Auth\app\routes.py:41]
2024-11-27 17:27:15,014 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:29:46,680 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:29:57,300 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:30:34,306 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:30:41,576 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:30:45,260 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:30:49,315 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:34:20,303 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:34:24,975 ERROR: RSAΩ‚√‹¥ÌŒÛ: RSA key format is not supported [in d:\Code\project\Auth\app\utils.py:105]
2024-11-27 17:34:24,976 ERROR: Ω‚√‹ ß∞‹: RSA key format is not supported [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:36:22,771 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:36:25,373 ERROR: RSAΩ‚√‹¥ÌŒÛ: Not a valid PEM pre boundary [in d:\Code\project\Auth\app\utils.py:105]
2024-11-27 17:36:25,374 ERROR: Ω‚√‹ ß∞‹: Not a valid PEM pre boundary [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:37:20,055 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:37:27,688 ERROR: RSAΩ‚√‹¥ÌŒÛ: Not a valid PEM pre boundary [in d:\Code\project\Auth\app\utils.py:105]
2024-11-27 17:37:27,688 ERROR: Ω‚√‹ ß∞‹: Not a valid PEM pre boundary [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:37:37,475 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:37:46,216 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:37:48,032 ERROR: RSAΩ‚√‹¥ÌŒÛ: Ciphertext too large [in d:\Code\project\Auth\app\utils.py:104]
2024-11-27 17:37:48,032 ERROR: Ω‚√‹ ß∞‹: Ciphertext too large [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:44:55,150 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 17:44:55,150 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:46:36,307 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:46:39,713 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:46:41,488 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:46:46,289 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:46:48,291 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:47:02,862 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:47:09,418 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:47:10,124 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:47:14,310 ERROR: RSAΩ‚√‹¥ÌŒÛ: Ciphertext with incorrect length. [in d:\Code\project\Auth\app\utils.py:106]
2024-11-27 17:47:14,310 ERROR: Ω‚√‹ ß∞‹: Ciphertext with incorrect length. [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:47:19,254 INFO: Authentication system startup [in d:\Code\project\Auth\app\__init__.py:28]
2024-11-27 17:47:20,911 ERROR: Ω‚√‹ ß∞‹: object of type 'NoneType' has no len() [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:48:57,279 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 17:48:57,280 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:51:00,375 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 17:51:00,375 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:52:46,673 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 17:52:46,674 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:53:14,961 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 17:53:14,961 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
2024-11-27 17:57:02,394 ERROR: AESΩ‚√‹¥ÌŒÛ: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\utils.py:86]
2024-11-27 17:57:02,395 ERROR: Ω‚√‹ ß∞‹: Incorrect AES key length (0 bytes) [in d:\Code\project\Auth\app\routes.py:37]
